
all: 
	cd 3ddemo; make
	cd Fireworks; make
	cd matrix; make
	cd gears; make
	cd imgui_demo; make

clean:
	cd 3ddemo; make clean
	cd Fireworks; make clean
	cd matrix; make clean
	cd gears; make clean
	cd imgui_demo; make clean