
all: 
	cd emu; make
	cd macintosh; make
	cd snake; make
	cd mandelbrot; make
	cd saver; make

clean: 
	cd emu; make clean
	cd macintosh; make clean
	cd snake; make clean
	cd mandelbrot; make clean
	cd saver; make clean
