
all: 
	cd minivmac; make
	cd mandelbrot; make
	cd saver; make
	cd emu; make
	cd kimi_chat; make
	cd xDraw; make

clean: 
	cd minivmac; make clean
	cd mandelbrot; make clean
	cd saver; make clean
	cd emu; make clean
	cd kimi_chat; make clean
	cd xDraw; make clean
